---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: master-debian-10
    image: docker.io/geerlingguy/docker-debian10-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - master
  - name: master-ubuntu-1804
    image: docker.io/geerlingguy/docker-ubuntu1804-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - master
  - name: master-centos-8
    image: docker.io/geerlingguy/docker-centos8-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - master
provisioner:
  name: ansible
  # log: true
verifier:
  name: ansible
scenario:
  name: default
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence # deleting existing files before download cause this to fail.
    - side_effect
    - verify
    - cleanup
    - destroy
