---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: master-debian-10
    image: docker.io/geerlingguy/docker-debian10-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - master
  - name: master-ubuntu-1804
    image: docker.io/geerlingguy/docker-ubuntu1804-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - master
  - name: master-centos-8
    image: docker.io/geerlingguy/docker-centos8-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - master
  - name: node-debian-10
    image: docker.io/geerlingguy/docker-debian10-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - node
  - name: node-ubuntu-1804
    image: docker.io/geerlingguy/docker-ubuntu1804-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - node
  - name: node-centos-8
    image: docker.io/geerlingguy/docker-centos8-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - node
provisioner:
  name: ansible
  # log: true
verifier:
  name: ansible
